### ISSUE TITLE
More compact `ParsedIriRef`.

### ISSUE THREAD

**Issue by timothee-haudebourg** [timothee-haudebourg/iref#10]
For now the metadata type `ParsedIriRef` is defined using `usize` and `Option<usize>`. This is far for optimal since:
 - the large majority of IRIs don't take more that 255 characters (mostly for compatibility reasons). Most of the `usize` space is wasted.
 - `Option<usize>` takes even more space.

This can be improved by:
 - using `u32`, `u16` or even `u8` instead of `usize`. This could be a parameter of `ParsedIriRef` (with a default to `u16`?).
 - using [non-zero integers](https://doc.rust-lang.org/std/num/struct.NonZeroU16.html) to avoid wasting space with an `Option`.

This could come with a variety of type aliases such as `SmallIri` for `Iri<u8>` for instance.

**Comment by MattesWhite** [comment]
> - the large majority of IRIs don't take more that 255 characters (mostly for compatibility reasons). Most of the `usize` space is wasted.

Correct, as `ParsedIriRef` only stores the length of the IRI parts giving each `u8` or `NonZeroU8` should be fine. The only exception I would make is for `path_len`. Especially in RDF I saw IRI that might have more than 255 characters in their path. But `u16` should be enough for that.

> - using u32, u16 or even u8 instead of usize. This could be a parameter of ParsedIriRef (with a default to u16?).

I'm a big fan of a blog post from matklad the main-maintainer of Rust Analyzer: [Code Smell: Concrete Abstraction](https://matklad.github.io/2020/08/15/concrete-abstraction.html). The _tl;dr_ is that if you do not have a concrete scenario where you can benefit from parameterizing a type you shouldn't do it.

All in all, my suggestion is to set every length to `u8`, except for `path_len` that should be `u16`. Every `Option<usize>` should be turned into `Option<NonZeroU8>`. The 'offset' methods should still return `usize`. `ParsedAuthority` should get the same treatment.
