### ISSUE TITLE
"//1.1.1.1a", "//1.1.1.1111" & "//[1::]" misinterpreted to have invalid path

### ISSUE THREAD

**Issue by yescallop** [timothee-haudebourg/iref#15]
According to RFC 3986, "1.1.1.1a" and "1.1.1.1111" are both valid `reg-name`s, while `[1::]` is a valid IPv6 literal. However, `IriRef::from_str` parses them as having "invalid path". These cases were found when fuzzing [`fluent-uri`](https://github.com/yescallop/fluent-uri-rs) against this crate.

**Comment by timothee-haudebourg** [comment]
Thanks for the bug report, I'll try to fix that right away

**Comment by yescallop** [comment]
I fuzz-tested again with the latest fix and still found cases like `\\[::1]` and `\\[1::1]` failing. Here's my fuzz target against `iref` and I hope this helps:
[against_iref.rs](https://github.com/yescallop/fluent-uri-rs/blob/fuzz_against_iref/fuzz/fuzz_targets/against_iref.rs)

**Comment by timothee-haudebourg** [comment]
Ah I forgot `]` in the follow set for the `h16` rule. Yes I think I'll implement a similar testing infrastructure to be more thorough.

**Comment by yescallop** [comment]
Yeah I think maybe you can try to fuzz-test this crate against `iri-string`. I've tried this with four crates and found bugs in each of them (including mine).

**Comment by timothee-haudebourg** [comment]
This should not be an issue anymore as the IRI parser is now automatically generated from the ABNF grammar. Feel free to reopen is the issue is still there, but that would mean there is an issue with the [`static-regular-grammar`](https://crates.io/crates/static-regular-grammar) crate and no this one directly.
