### ISSUE TITLE
BStr?

### ISSUE THREAD

**Issue by Longor1996** [timothee-haudebourg/iref#19]
I would like to use iref to parse URIs that contain non-encoded/raw binary data (via a custom `binary:`-scheme) which means, unfortunately, that I cannot use `str` as that'd be invalid UTF-8.

Is it possible to make a feature that uses the `bstr`-crate instead, or would that require a full rewrite (a fork?)?

**Comment by timothee-haudebourg** [comment]
Unfortunately the URI syntax defined in [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) does not allow for non ASCII bytes, so what you described is, by definition, not an URI. You would need to define a superset of URIs (and IRIs for that matter), which is feasible but outside of the scope of this crate.

**Comment by Longor1996** [comment]
Ah, that is unfortunate but understandable.

Then... how hard would it be, in theory(?), to port the parsing logic to use BStr in a new crate?

**Comment by timothee-haudebourg** [comment]
I've developed a crate called [`static-regular-grammar`](https://github.com/timothee-haudebourg/static-regular-grammar/) to generate all the parsers in this library from the ABNF grammar specification. It can handle non-ASCII/Unicode grammars, so in theory you could use it and adjust the URI grammar to fit your needs.

**Comment by Longor1996** [comment]
Thank you *very* much, that is an awesome crate! :)

Closing issue.
