### ISSUE TITLE
Implement convenience traits

### ISSUE THREAD

**Issue by MattesWhite** [timothee-haudebourg/iref#6]
First of all thank you for this crate. It works well and suits my use-case.

However, the handling is a little bit inconvenient. All conversions are done via `From` and `TryFrom` or `new()` constructors. As a result, I had to reference the docs a lot while programming.

Accordingly, I suggest to implement the usual convenience traits to improve the usability of `iref`, e.g. [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html), [`ToOwned`](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html) and [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html).

I read that you want to wait for [custom DSTs](https://github.com/rust-lang/rfcs/pull/2594) to land. However, the latest comments mentioned that the feature is not part of the 2021 roadmap. So I think its save to assume that the feature won't land for quite some time.

If you agree I would be glad to write a PR. I have a couple of more ideas to improve usability, e.g. using rustfmt and clippy, but for now that's enough.

**Comment by timothee-haudebourg** [comment]
Hi,

Thanks for the feedback. That seems like some good ideas, I'll be glad to take a look at your PR :smile: 

> I read that you want to wait for custom DSTs to land

That's right, but that will be for a next major release, nothing stops us from improving this version without it.

> using rustfmt and clippy

I don't mind, but I would prefer having those in a separate PR. The only condition I have is keeping the hard tabs for accessibility purposes by putting a `.rustfmt.toml` file with `hard_tabs = true`.
